# backend/webserver/config/config.yml
PROJECT_NAME: 'ADI'
fastapi:
  debug: true


databases:

  mongo:
    ENGINE: 'mongodb'
    DRIVER: 'motor'
    NAME: 'webserver'
    USER: 'admin'
    PASSWORD: 'admin'
    HOST: 'mongo_db'
    PORT: 27017
    DROP_COLLECTION_ON_START: ["sdad"]
    DB_PREPARATION:
      security:
        index:
          username
          email
      customer:
        index:
          customer_no
          email

    WATCH: ["customer","test"]

  postgres:
    ENGINE: 'postgres'
    NAME: 'demo'
    USER: 'admin'
    PASSWORD: 'admin'
    HOST: 'postgres'
    PORT: 5432
  redis:
    host: redis_db
    port: 6379
    db: 0


files:
  default:
    input_file_path: '/webserver/input/'
    output_file_path: '/webserver/output/'

security:
   trace_request: 'Y'